### ISSUE TITLE
类型转换异常

### ISSUE THREAD

**Issue by Movement123** [kymjs/TheMVP#9]
java.lang.NoClassDefFoundError: Failed resolution of: Landroid/databinding/DataBinderMapper;
                                                                  at android.databinding.DataBindingUtil.<clinit>(DataBindingUtil.java:31)
                                                                  at com.kymjs.themvp.view.AppDelegate.create(AppDelegate.java:43)
                                                                  at com.kymjs.themvp.presenter.ActivityPresenter.createBinding(ActivityPresenter.java:59)
                                                                  at com.kymjs.themvp.presenter.ActivityPresenter.onCreate(ActivityPresenter.java:51)
                                                                  at android.app.Activity.performCreate(Activity.java:6303)
                                                                  at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
                                                                  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2376)
                                                                  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2483)
                                                                  at android.app.ActivityThread.access$900(ActivityThread.java:153)
                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1349)
                                                                  at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                  at android.os.Looper.loop(Looper.java:148)
                                                                  at android.app.ActivityThread.main(ActivityThread.java:5438)
                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)
                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629)

**Comment by kymjs** [comment]
看demo里的用法
